spring:
  mail:
    host: smtp.yandex.ru
    username: DmitryXox02
    password: yakktqseuizdyoza
    port: 465
    protocol: smtp

  kafka:
    consumer:
      bootstrap-servers: "localhost:9092"
      group-id: "dossier"

#  jackson:
#    deserialization:
#      read-unknown-enum-values-as-null: true

mail:
  debug: true

application:
  kafka:
    topics:
      - finish-registration: "finish-registration"
      - create-documents: "create-documents"
      - send-documents: "send-documents"
      - send-ses: "send-ses"
      - credit-issued: "credit-issued"
      - application-denied: "application-denied"